### ISSUE TITLE
Prevent Repeat Broadcasts

### ISSUE THREAD

**Issue by Furgl** [xPXpanD/PixelmonBroadcasts#10]
**Feature suggestion: Prevent repeat broadcasts to avoid spam like below (i.e. when trying to catch a legend with quick balls)**

![image](https://user-images.githubusercontent.com/16003461/123696006-df30c300-d820-11eb-8145-54efc693fe24.png)

One way this could be achieved is by tracking the EventData, player UUID, and Pokemon UUID that triggers each broadcast and cancelling the broadcast if it matches those from a previous broadcast.

**Comment by xPXpanD** [comment]
Oops, forgot to reply here as well. This has been on my radar for a bit, need to look into this at some point. Not gonna set a milestone just yet (no time at the moment), but I'll keep it in mind! Thanks for the report.

**Comment by xPXpanD** [comment]
Closing this issue (and the project in general) due to me recently having been booted off of the Pixelmon mod team over a minor disagreement, if you can even call it that. Guess that's what 5.5 years on the team gets you... The code's still public and the license is permissive if people want to keep working on it, but I am unable to continue working on these projects myself. Sorry for the bad news.
