### ISSUE TITLE
HA Announcement

### ISSUE THREAD

**Issue by Coder-Lynx** [xPXpanD/PixelmonBroadcasts#9]
**Feature Request**

Add a HA announcement module to PixelmonBroadcasts

**Comment by xPXpanD** [comment]
Sounds good, will have a look for 0.6.2 when I eventually start work on that. Thanks for the suggestion.

**Comment by xPXpanD** [comment]
Closing this issue (and the project in general) due to me recently having been booted off of the Pixelmon mod team over a minor disagreement, if you can even call it that. Guess that's what 5.5 years on the team gets you... The code's still public and the license is permissive if people want to keep working on it, but I am unable to continue working on these projects myself. Sorry for the bad news.
